CREATE DATABASE IF NOT EXISTS DB_NAME;

CREATE USER 'root'@'localhost' IDENTIFIED BY 'mysql_root_password';
GRANT ALL PRIVILEGES ON *.* TO 'root'@'localhost' WITH GRANT OPTION;
CREATE USER DB_USER@'%' IDENTIFIED BY DB_PSW;
GRANT ALL PRIVILEGES ON *.* TO DB_USER@'%' WITH GRANT OPTION;

FLUSH PRIVILEGES;
