echo "CREATE DATABASE IF NOT EXISTS ${DB_NAME};
GRANT ALL PRIVILEGES ON *.* TO root@localhost WITH GRANT OPTION;
CREATE USER ${DB_USER}@localhost IDENTIFIED BY '${DB_PSW}';
GRANT ALL PRIVILEGES ON *.* TO ${DB_USER}@localhost WITH GRANT OPTION;
ALTER USER root@localhost IDENTIFIED BY '${MYSQL_ROOT_PASSWORD}';" > base_wp.sql