CREATE DATABASE IF NOT EXISTS DB_NAME;

ALTER USER 'root'@'localhost' IDENTIFIED BY 'mysql_root_password';
GRANT ALL PRIVILEGES ON *.* TO 'root'@'localhost' WITH GRANT OPTION;
CREATE USER 'db_user'@'%' IDENTIFIED BY 'db_psw';
GRANT ALL PRIVILEGES ON *.* TO 'db_user'@'%' WITH GRANT OPTION;

FLUSH PRIVILEGES;
