echo "CREATE DATABASE IF NOT EXISTS ${DB_NAME};
GRANT ALL PRIVILEGES ON *.* TO root@localhost WITH GRANT OPTION;
CREATE USER ${DB_USER}@localhost IDENTIFIED BY '${DB_PSW}';
GRANT ALL PRIVILEGES ON *.* TO ${DB_USER}@localhost WITH GRANT OPTION;
FLUSH PRIVILEGES;
ALTER USER root@localhost IDENTIFIED BY '${MYSQL_ROOT_PASSWORD}';
FLUSH PRIVILEGES;" > base_wp.sql